import './globals.css'
import type { Metadata } from 'next'
import { Inter, Rubik } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const rubik = Rubik({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Chat-ia',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>{children}</body>
    </html>
  )
}
